server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://rmatsdb.csryqq1q1rwd.eu-west-1.rds.amazonaws.com:3307/rMATS
    username: root
    password: password1234

  jpa:
    hibernate:
      ddl-auto: validate


