spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_rmats?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password1234

  jpa:
    hibernate:
      ddl-auto: validate


